# =====================
# CONFIGURACIÓN BASE DE DATOS
# =====================
spring.datasource.url=jdbc:mysql://localhost:3306/gestionfp?useSSL=false&serverTimezone=Europe/Madrid
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
# create-drop: borra y crea las tablas cada vez que arrancas (útil en desarrollo)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# =====================
# CONFIGURACIÓN EMAIL (Gmail)
# =====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hamebetico@gmail.com
spring.mail.password=qztc pydb ybch kcwo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =====================
# THYMELEAF
# =====================
spring.thymeleaf.cache=false

# =====================
# SUBIDA DE FICHEROS (para el CSV)
# =====================
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Puerto del servidor
server.port=8080

# =====================
# # Internacionalización - ficheros en la raíz de resources
# =====================
spring.messages.basename=messages
spring.messages.encoding=UTF-8